### ISSUE TITLE
PR?

### ISSUE THREAD

**Issue by pablos-here** [uberkael/awk-yasnippets#1]
Hi,

I'm unsure whether I want to fork or PR.   

Are you taking PRs?   If so, how keen are you on formatting changes too?   It's simply a preference which is why I'm thinking of forking.  :)

For example instead of:

```awk
if(${1:condition}){
    $0
}
```

I prefer spaces:

```awk
if (${1:condition}) {
    $0
}
```

**Comment by pablos-here** [comment]
Hi, I've created a PR in repository that has a collection of snippets:  https://github.com/AndreaCrotti/yasnippet-snippets/pull/463

**Comment by uberkael** [comment]
Hi!
For some reason, I didn't get the notifications.
It's been too long since I made this, since then I also prefer that style :D
I can accept PR

**Comment by pablos-here** [comment]
Hi,

The other project is in MELPA so there would be a wider audience.  I think it might be best to have them collected there.

**Comment by uberkael** [comment]
Sure.

**Comment by pablos-here** [comment]
Hi @uberkael ,

I have not been able to get any traction from the other project.  

Let me know if you'd like me to submit the PR here.  It'd be great to eventually look at submitting the package to MELPA too.

**Comment by pablos-here** [comment]
Hey @uberkael,

The other project seems to be idle.  If you're still interested, I can push the PR here instead.  It'd be great to also figure out how to get it into MELPA.  The de facto naming convention would be `awk-yasnippets`.  This means you'd probably want to rename this repository.

I'd understand if you're not interested.  In which case, I'll fork and rename accordingly.

Thanks a lot!

**Comment by uberkael** [comment]
Hi,
Ok, I  can rename it and accept a PR.
Maybe I can ask how to put it on MELPA too.

**Comment by uberkael** [comment]
Merged
