### ISSUE TITLE
Promote package to MELPA

### ISSUE THREAD

**Issue by pablos-here** [uberkael/awk-yasnippets#4]
Hi @uberkael ,

Here are instructions on how to get this repository included on [MELPA](https://melpa.org/#/):

https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org

Let me know if you need help in setting it up.  I have never done so but my motto is ... how hard can it be?  :)

Thx!

**Comment by uberkael** [comment]
Seems like I will have a busy week, I will take a look but feel free to submit it to melpa if you have the time.

**Comment by pablos-here** [comment]
I might be able to have a look later this week.  When you are ready, 
please post back so I can let you know how far (if at all!), I made it.  :)

**Comment by pablos-here** [comment]
Hi @uberkael ,

I finally had time to read the documentation.  In the first [section](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#contributing-a-new-recipe-to-melpa),

First, it states:
>MELPA consists of recipes, each describing one package in a dedicated repository.

and further:
> We advise package authors to also take the recipe author role when possible

where the recipe author is:
>... responsible for submitting good recipes and maintaining them when the package is changed (e.g., renamed or deprecated).

Basically they are recommending that you, as this project's author should also be the recipe author.  You'll be needing to do a PR against `MELPA` to submit the recipe.

When do you think you'll have time to submit the recipe?

Thx a lot!

**Comment by uberkael** [comment]
Thanks,
I will take a look during the weekend.

**Comment by pablos-here** [comment]
If you need a hand, just let me know.  Thank you so much!

**Comment by uberkael** [comment]
PR submitted at (https://github.com/melpa/melpa/pull/8471)

**Comment by pablos-here** [comment]
Hi @uberkael ,

I see in the above PR, they're currently waiting over two weeks for you to act.  Do you have a general idea of when you might be able to respond?

**Comment by uberkael** [comment]
Hi, @pablos-here 
Sorry for the delay.
It was merged into MELPA here https://github.com/melpa/melpa/commit/d25b1b6391e01096d6d3551db6c67ad7830771c2
Thanks!

**Comment by pablos-here** [comment]
Hi @uberkael ,

Well done and kind words from [them](https://github.com/melpa/melpa/pull/8471#issuecomment-1546953878 ):

> This produces an interesting shorthand for writing awk.
