### ISSUE TITLE
MELPA description is sparse

### ISSUE THREAD

**Issue by pablos-here** [uberkael/awk-yasnippets#5]
Hi,

When you get a chance, you should update the MELPA **Description** from _Quick intro_ (which I believe is a placeholder) to something more descriptive:

![image](https://github.com/uberkael/awk-yasnippets/assets/2430861/d4332724-3c09-4991-a031-98675dd1513f)

Perhaps:

> A collection of snippets to expedite writing AWK scripts.

**Comment by uberkael** [comment]
This should do the trick 12e8e0b
Interestingly almost none of the other Yasnippets have descriptions (except for Common Lisp and Haskell).

**Comment by pablos-here** [comment]
> This should do the trick [12e8e0b](https://github.com/uberkael/awk-yasnippets/commit/12e8e0b49878099bda5d3e4915cc3c738c87b95c) 

Thank you so much!  

>Interestingly almost none of the other Yasnippets have descriptions (except for Common Lisp and Haskell).

That is interesting eh?  The packages I've pulled from MELPA seem to have had descriptions.  I must have just got lucky.

Take care!
